Repository dbstj0403/js-practice, pull requests merged in 2025-04, with the labels that each got.

#2 Feat: 상단 NavBar 구현
  img/navBar/icons.png
  img/navBar/logo.png
  index.css
  index.html
  index.js
Labels: feat

#5 Feature/festival info
  constants/festivalData.js
  festival/draggable.js
  festival/festivalInfo.html
  festival/festivalInfo.js
  index.css
  index.html
  layouts/footer.html
  layouts/navBar.html
Labels: design

#7 Docs: Readme 폴더 구조 추가
  README.md
  index.js
Labels: documentation

#8 Chore: 주석 추가 및 행사 정보 카드 디자인 수정
  constants/eventData.js
  event/event.html
  event/event.js
  festival/festivalInfo.html
  festival/festivalInfo.js
  img/festival/calendarIcon.png
  img/festival/nextIcon.png
  img/festival/prevIcon.png
  index.html
Labels: design

#10 Feat: 슬라이드 떠오르는 hover 구현
  eventSlider/eventSlider.html
  img/eventSlider/btn_next.png
  img/eventSlider/btn_prev.png
Labels: design

#11 Feat: 행사 정보 카드 인디케이터 구현
  constants/eventData.js
  constants/festivalData.js
  event/event.js
  festival/festivalInfo.html
  festival/festivalInfo.js
  img/event/event7.png
  img/event/event8.png
Labels: feat, design

#13 Chore: 이벤트 날짜 수정
  constants/eventData.js
Labels: chore

#12 Fix: 슬라이드 진행바 수정 및 동적으로 길이 계산하도록 변경
  eventSlider/eventSlider.html
  eventSlider/eventSlider.js
Labels: bug
